# purple-hotline for Pidgin on Windows: libhotline.dll.
#
# Pidgin 2.14 for Windows is a 32-bit program, so this builds 32-bit (i686) with
# MinGW-w64, either in MSYS2's MINGW32 shell or as a cross compiler elsewhere:
#
#   make -f Makefile.mingw PIDGIN_TREE_TOP=../pidgin-2.14.14 WIN32_DEV_TOP=../win32-dev
#
# PIDGIN_TREE_TOP  Pidgin's source (for libpurple's headers and libpurple/win32)
# WIN32_DEV_TOP    Pidgin's win32-dev bundle (glib's headers and import libraries)
# PURPLE_DLL_DIR   a folder holding libpurple.dll (an installed Pidgin's, or a build's)
#
# Install: libhotline.dll into %APPDATA%\.purple\plugins, and the icons under
# pidgin\pixmaps\ into Pidgin's own pixmaps\pidgin\protocols\ (the installer does both).

CC ?= i686-w64-mingw32-gcc
PIDGIN_TREE_TOP ?= ../pidgin-2.14.14
WIN32_DEV_TOP ?= $(PIDGIN_TREE_TOP)/../win32-dev
GTK_TOP ?= $(WIN32_DEV_TOP)/gtk2-2.24
PURPLE_DLL_DIR ?= $(PIDGIN_TREE_TOP)/libpurple

CFLAGS ?= -O2 -g
CFLAGS += -Wall -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations \
	-DPURPLE_PLUGINS -DWIN32_LEAN_AND_MEAN \
	-I$(PIDGIN_TREE_TOP)/libpurple -I$(PIDGIN_TREE_TOP)/libpurple/win32 \
	-I$(GTK_TOP)/include/glib-2.0 -I$(GTK_TOP)/lib/glib-2.0/include
LIBS = -L$(GTK_TOP)/lib -lglib-2.0 -L$(PURPLE_DLL_DIR) -lpurple -lws2_32

SRC = src/hotline.c src/hl_wire.c src/hl_crypto.c src/hl_json.c src/hl_tracker.c src/hl_room.c

all: libhotline.dll

libhotline.dll: $(SRC) src/*.h
	$(CC) $(CFLAGS) -shared -o $@ $(SRC) $(LIBS) -Wl,--enable-auto-image-base

clean:
	rm -f libhotline.dll

.PHONY: all clean
